# Generated by Django 3.2.6 on 2021-08-26 19:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Categoria de Link',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('tenant_id', models.CharField(max_length=100)),
                ('school_id', models.CharField(max_length=100)),
                ('acessar', models.CharField(max_length=50)),
                ('login', models.CharField(blank=True, max_length=50)),
                ('senha', models.CharField(blank=True, max_length=70)),
                ('data_cadastro', models.DateField(default=datetime.date.today)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='links.categorialinks')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link',
            },
        ),
    ]
